export const SET_REQUESTS = "SET_REQUESTS";
export const SET_CLIENT_TO_SERIVICE_REQUEST = "SET_CLIENT_TO_SERIVICE_REQUEST";
export const SET_LOADING = "SET_LOADING";
export const REMOVE_CLIENT = "REMOVE_CLIENT";
